version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: easyticketdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - /c/Users/yarin/OneDrive/Desktop/easytickets_dump.sql:/docker-entrypoint-initdb.d/dumpfile.sql

  redis:
    image: redis
    ports:
      - "6379:6379"

  #  It builds the image for the app using the Dockerfile found in the same directory.
  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/easyticketdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_REDIS_HOST: redis
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"

volumes:
  postgres-data: